return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "master",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = {
          'arduino',
          'asm',
          'awk',
          'bash',
          'c',
          'caddy',
          'clojure',
          'cmake',
          'commonlisp',
          'cpp',
          'c_sharp',
          'css',
          'csv',
          'cuda',
          'd',
          'dart',
          'devicetree',
          'diff',
          'dockerfile',
          'elixir',
          'elm',
          'go',
          'gomod',
          'gosum',
          'html',
          'javascript',
          'json',
          'lua',
          'make',
          'objc',
          'objc',
          'ocaml',
          'odin',
          'php',
          'python',
          'ruby',
          'rust',
          'svelte',
          'terraform',
          'toml',
          'typescript',
          'xml',
          'yaml',
          'zig',
        },
        auto_install = true,
        highlight = {
          enable = true,
          -- set to true to run `:h syntax` and tree-sitter together.
          -- can also set it to a list of languages
          additional_vim_regex_highlighting = false,
        },
        indent = {
          enable = true,
        },
        incremental_selection = {
          enable = true,
          keymaps = {
            init_selection = "gnn",
            node_decremental = "grm",
            node_incremental = "grn",
            scope_incremental = "grc",
          },
        },
      })
    end,
  }
}
