# All shells (1)

#
# Paths

TRY_PATHS=(
  "${HOME}/bin"
  "${HOME}/.dotfiles/bin"
  "${HOME}/.cargo/bin"
)

for try_path in $TRY_PATHS
do
  [[ -d "$try_path" ]] && export PATH="${try_path}:${PATH}"
done
