# All shells (1)

#
# Paths

TRY_PATHS="
  ${HOME}/bin
  ${HOME}/.dotfiles/bin
  /opt/local/bin
  /opt/local/sbin
  /opt/jruby/bin
  /opt/scala/bin
  /usr/local/mysql/bin
  ${HOME}/dev/tools/depot_tools
"

for try_path in $TRY_PATHS
do
  [[ -d $try_path ]] && PATH=${PATH}:${try_path}
done